Pint 965 flashpoint indicator intelligence feed
eclecticiq/extensions-store pull request #100
Opened 2023-04-20 13:27 UTC by canic-eiq

2023-04-21 12:50 UTC, petarc-eiq requested changes

2023-04-21 12:50 UTC, petarc-eiq commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/manifest.json
> +  "version": "0.1.0",
version should be 1.0.0

2023-04-21 12:50 UTC, petarc-eiq commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/manifest.json
> +        "flashpoint_extension"
flashpoint_indicator_intelligence

2023-04-21 12:50 UTC, petarc-eiq commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/process.py
> +        headers = {"Authorization": f"token {api_key}", "User-Agent": USER_AGENT}
"User-Agent" header should be: `f"{self.manifest['name']} version:{self.manifest['version']}"`

2023-04-21 12:50 UTC, petarc-eiq commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/process.py
> +        log.info("Flashpoint indicator intelligence started downloading data")
No need for `log.info()` when there's `self.send_info()`

2023-04-21 12:50 UTC, petarc-eiq commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/manifest.json
> +          "default": "https://fp.tools/api/v4/indicators/attribute",
Default URL should be `https://fp.tools` and `api/v4/indicators/attribute` should be the endpoint we're sending requests to.

2023-04-21 12:50 UTC, petarc-eiq commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/transformer.py
> +        "attack" : [],
"attack" is redundant.

2023-04-21 12:50 UTC, petarc-eiq commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/utils.py
> +)
USER_AGENT is generated in MainApp, so it can be removed from here.

2023-04-21 12:50 UTC, petarc-eiq commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/utils.py
> +        report_url = api_url.replace("indicators/attribute", "reports/")
This is why we should change the api_url to be proper API URL, so that we can add endpoints and create URLs instead of doing gymnastics like this. When we change the default URL, this will change to something like 
`furl(api_url).add(path="api/v4/reports")`

2023-04-21 12:50 UTC, petarc-eiq commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/utils.py
> +            report_url = api_url.replace("/indicators/attribute", source.get("source"))
Again, when we change the default URL, this will change to something like 
`furl(api_url).add(path="api/v4/source")`

2023-04-26 07:59 UTC, zoranjovevski commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/LICENSE.md
> +# The MIT License (MIT)
Change the license

2023-04-26 08:05 UTC, zoranjovevski commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/transformer.py
> +    log.info("Transformer started")
Remove this line.

2023-04-26 08:05 UTC, zoranjovevski commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/transformer.py
> +    log.info("Transformer finished successfully")
Remove this line.

2023-04-26 08:10 UTC, zoranjovevski commented on extensions/flashpoint/incoming_feeds/flashpoint_indicator_intelligence_feed/transformer.py
> +
Remove empty line

2023-05-04 11:44 UTC, zoranjovevski approved these changes

2023-05-04 12:17 UTC, merged