Add documentation to README.rst
eclecticiq/extensions-store pull request #116
Opened 2023-05-05 07:44 UTC by nathan-eiq

Part of [DEV-5140](https://eclecticiq.atlassian.net/browse/DEV-5140)

- Added documentation to README.rst

2023-05-05 08:45 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +.. list-tables::
add one more space!

`.. list-tables::` -> `..  list-tables::`

need to align indentation for tables to properly render :sweat_smile:

2023-05-05 08:46 UTC, zed-eiq commented
other than my comment about indentation, it looks good! thank you! :pray:

2023-05-05 11:29 UTC, zed-eiq commented
also please follow the PR naming convention `[<ticket#>] <purpose of PR>`!

2023-05-07 19:59 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +.. list-tables::
just realised -- like in #118 , this should be `list-table` :grin:

2023-05-26 10:50 UTC, petarc-eiq requested changes

2023-05-26 10:50 UTC, petarc-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +    "Classification","classification","array","true","Include indicators with selected classification",""
default="malicious"

2023-05-26 10:50 UTC, petarc-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +Supported Observable types
This section is applicable only to Enrichers.

2023-05-26 13:56 UTC, nathan-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +Supported Observable types
I see what you mean. That is indeed where the section name comes from. The idea behind this section is to tell the users what entities they will get from the extension. I'll change that to make clearer

2023-05-26 15:55 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +Supported Observable types
just remove! see https://github.com/eclecticiq/extensions-store/pull/120/files/c725ca60ad05161cfd7e3173a767b6ce4b96f33b..a95cf3fa7ad3809f7bb8deaa1e7c69b28afb2e59#r1206994028

2023-05-30 07:58 UTC, nathan-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +Supported Observable types
Done

2023-06-07 08:13 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +      - ``<country>``
these EIQ JSON values should be JSONpath-like things, right? instead, i think you've taken the 'value' portion of the mapping where we need the JSONpath/key of the EIQ JSON that this data is mapped to.

Same for all other EIQ JSON table cells here and probably in the other GreyNoise exts

2023-06-07 08:22 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +--------------
rename to "Map to observables"

2023-06-07 08:34 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +      - Data format
remove the data format column entirely

2023-06-07 08:34 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +Tags table
Rename "Map to tags"

2023-06-07 08:34 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +
Unclear that this section is describing data that is essentially just ingested as tags.

This means that
- when the feed is run, the objects generated (`indicator` objects in this case) are the anchoring object, and all the data here are added as tags on the anchoring object
- that "data formats" here are irrelevant/incorrect.

you can also see in the MR here that for specific GNQL JSON fields ingested as tags, we format these tags in a specific way: https://github.com/eclecticiq/extensions-store/pull/114/files#diff-7940a9fcff55a64b8bd438807e6103e158f8736c01b7b64f5a2957003bf35bceR116

e.g. for `data.spoofable`, we add a tag that looks like `Spoofable: <value>`

2023-06-07 08:36 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +This extension maps data from GNQL JSON to EIQ JSON format.
This extension processes responses from GNQL queries to produce EclecticIQ Indicator entities.
The following sections show how GNQL JSON is mapped to Indicator entities in EIQ JSON.

2023-06-07 09:33 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +      - EIQ JSON
- your first column is actually the EIQ JSON field name
- your last column is a description of the data

2023-06-09 10:03 UTC, zed-eiq requested changes
More changes!
Also, please rebase your branch on petar's latest changes :pray:

2023-06-09 10:03 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +    * - Description
Remove the `Description` column

- Doesn't add value here
- `Description` should never be the first column. You want a short, maybe sortable value for the first column of the table (i.e. "primary key-ish" value)

2023-06-09 10:03 UTC, zed-eiq commented on extensions/greynoise/incoming_feeds/greynoise_noise_incoming_feed_v1/README.rst
> +    * - Field Name
can't remember where the feedback was given elsewhere, but basically the table headings here don't make sense.

- first column is EIQ JSON fields
- third column can be named `Description`

2023-06-15 09:13 UTC, zed-eiq commented
thanks! the README.rst file looks good now!

can you fix the rebase?
- you might have rebased it on an outdated (local) version of the target branch
- or you might have rebased on the wrong branch

alternatively, close this MR and start a new one referencing this one :+1:

2023-06-15 09:22 UTC, closed without merging