Verification and ssl path updated
eclecticiq/extensions-store pull request #117
Opened 2023-05-05 13:20 UTC by canic-eiq

2023-05-18 15:58 UTC, petarc-eiq requested changes
small typos and such

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/group_ib/incoming_feeds/group-ib-attacks-phishing-kit/manifest.json
> +          "default": false,
Default value for "verify" should always be true.

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/manifest.json
> -          "name": "blacklist"
Be careful what you're replacing, you removed "blacklist" field and have 2 "verify" fields.

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/group_ib/incoming_feeds/group-ib-brand-abuse-phishing-kit/manifest.json
> +          "default": false,
Default value for "verify" should always be true.

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/group_ib/incoming_feeds/group-ib-compromised-data-accounts/manifest.json
> +          "default": false,
Default value for "verify" should always be true.

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/group_ib/incoming_feeds/group-ib-compromised-data-cards/manifest.json
> +          "default": false,
Default value for "verify" should always be true.

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/group_ib/incoming_feeds/group-ib-human-intelligence/manifest.json
> +          "default": false,
Default value for "verify" should always be true. (apply everywhere... :) )

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/group_ib/incoming_feeds/group_ib_attacks_phishing/manifest.json
> +        }s
Delete "s".

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/intel471/enrichments/adversary-intelligence-enricher/manifest.json
> +          "default": false,
Default value for "verify" should always be true.

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/intel471/enrichments/posts_enricher/manifest.json
> +          "default": false,
Default value for "verify" should always be true.

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/intel471/enrichments/posts_enricher/utils.py
> +            self, url=api_url, auth=auth, verify=verify_ssl, params=query_params
fetch_results parameter is `verify_ssl`, undo this change.

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/intel471/incoming_feeds/adversary_Intelligence_feed/main.py
> +                    self, report_url, auth=(api_email, api_key), verify=verify_ssl
fetch_results parameter is `verify_ssl`, so it should be `verify_ssl=verify_ssl`.

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/intel471/incoming_feeds/adversary_Intelligence_feed/manifest.json
> +          "default": false,
`"default": true,`

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/intel471/incoming_feeds/malware_feed/manifest.json
> +          "required": false,
`"default": true,`

2023-05-18 15:58 UTC, petarc-eiq commented on extensions/intel471/incoming_feeds/vulnerability_intelligence/manifest.json
> +          "default": false,
`"default": true,`

2023-06-05 12:34 UTC, petarc-eiq requested changes

2023-06-05 12:34 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/manifest.json
> +          "name": "verify"
Now there are 2 "verify" parameters. Still not good.

2023-06-05 12:34 UTC, petarc-eiq commented on extensions/flashpoint/incoming_feeds/flashpoint_reports_provider/manifest.json
> +          "default": true,
Did you mean to change this? This is cyber_threats, not verify :)

2023-06-05 13:03 UTC, petarc-eiq approved these changes

2023-06-13 08:12 UTC, erwin-eiq commented on extensions/intel471/enrichments/posts_enricher/utils.py
> +            self, url=api_url, auth=auth, verify=verify_ssl, params=query_params
@canic-eiq friendly ping on this comment :)

2023-06-13 08:12 UTC, erwin-eiq commented on extensions/intel471/incoming_feeds/adversary_Intelligence_feed/main.py
> +                    self, report_url, auth=(api_email, api_key), verify=verify_ssl
@canic-eiq friendly ping on this comment :)

2023-06-13 08:45 UTC, merged