[DEV-5140] Document Greynoise Enricher EDK protocol v1
eclecticiq/extensions-store pull request #118
Opened 2023-05-05 14:07 UTC by nathan-eiq

Part of [DEV-5140](https://eclecticiq.atlassian.net/browse/DEV-5140)

-  Added documentation to README.rst

2023-05-07 19:56 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +
you're missing one table header here, so your table won't render

2023-05-07 19:57 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +..  list-tables::
wrong directive name :sweat_smile: that's (one of the reasons) why your tables are not rendering

`list-tables` -> `list-table`

2023-05-26 11:18 UTC, petarc-eiq requested changes

2023-05-26 11:18 UTC, petarc-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +Suuported extract types:
Suuported > Supported

2023-05-26 11:18 UTC, petarc-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +- GreyNoise subscription with FEED access included
This is a bit confusing, what's "FEED access"? We ping 2 endpoints, so customers should have access to them: 
NOISE_CONTEXT_ENDPOINT = "v2/noise/context"
RIOT_ENDPOINT = "v2/riot"

2023-05-26 11:18 UTC, petarc-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +Using the submitted IP addresses as input and the complementary data provided by GreyNoise, this enricher creates EIQ JSON indicators with the following fields:
As written above, we send requests to 2 endpoints which return data from 2 datasets: 
NOISE dataset = "v2/noise/context"
RIOT dataset = "v2/riot"

Noise data is what's also processed by the incoming feed, in the way described here.

Riot data is different and we need to add a dedicated section for that. 
Here's an example:

```
{
	"ip": "1.1.1.1",
	"riot": true,
	"category": "public_dns",
	"name": "Cloudflare Public DNS",
	"description": "Cloudflare, Inc. is an American web infrastructure and website security company, providing content delivery network (CDN) services, distributed denial of service (DDoS) mitigation, Internet security, and distributed domain name system (DNS) services. This is their public DNS offering.",
	"explanation": "Public DNS services are used as alternatives to ISP's name servers. You may see devices on your network communicating with Cloudflare Public DNS over port 53/TCP or 53/UDP to resolve DNS lookups.",
	"last_updated": "2023-05-15T13:11:04Z",
	"reference": "https://one.one.one.one",
	"trust_level": "1"
}
```
This data produces just a single "company" observable (extract) with "name" ("Cloudflare Public DNS") field value.

2023-05-30 08:58 UTC, nathan-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +- GreyNoise subscription with FEED access included
That requirement comes from the following [comment](https://github.com/eclecticiq/extensions-store/issues/25#issuecomment-1440447141). I've added a reference to GreyNoise Customer service to answer the "What's FEED access" question.

As to either it covers access to both endpoints, that needs to be confirmed

2023-06-05 14:34 UTC, nathan-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +Using the submitted IP addresses as input and the complementary data provided by GreyNoise, this enricher creates EIQ JSON indicators with the following fields:
Will add the two endpoints in the specification table.

As for documenting the riot data, I am a bit at odds. The `create_indicator` function which I used to document the data mapping doesn't make distinction between the datasets provided by the two endpoints. I.e. I see only one way the data mapping is done.

Also if I interpret line 16 in process.py correctly, only entities containing an IP address and `"riot": true` are delivered. The rest is only found in the raw data.

2023-06-06 13:50 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +- API Key
sorry! one more: this should be `GreyNoise API key` instead -- because from the users' perspective, they're interacting with more than one API interface (e.g. EDK management API, GreyNoise, and whatever thing we're plugging the data into, which in this case is the IC)

2023-06-06 13:53 UTC, petarc-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +- URL to GreyNoise API
We can list the endpoints the extension is pinging if necessary, instead of saying "GreyNoise subscription with FEED access included". I think we discussed this already, maybe in another MR.

2023-06-06 13:54 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +    * -
sorry, one more: don't leave empty fields -- we want to be explicit if we are intentionally leaving things unspecified, or it'll just look like a mistake. If a field is not applicable, enter `N/A` or similar. If it it simply empty, leave an escaped dash `\-`

2023-06-06 14:57 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +- URL to GreyNoise API
yes! if API keys are scoped, then we should document the scopes (e.g. specific endpoints, permissions(?)) required to operate the enricher/feed

2023-06-06 15:18 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +      - See `Extract table`_
broken reference, please fix :pray:

2023-06-06 15:24 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +      - ``<item["first_seen"] in iso format>``
- consistency: remove angle brackets `<>`
- don't style `in iso format` as inline code. `item["first_seen"]` is actual syntax, but 'in iso format' is not. Instead, do something like
  > `item["first_seen"]` (ISO8601 timestamp)

2023-06-07 11:59 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +- URL to GreyNoise API
ah, now i see the previous convo :upside_down_face: https://github.com/eclecticiq/extensions-store/pull/118#discussion_r1210322646

but if i'm reading this correctly
- **this** (i.e. the enricher) needs GreyNoise Enterprise API access
- the incoming feed needs GreyNoise Enterprise API access _and_ FEED access included in their subscription.

2023-06-07 14:40 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +- GreyNoise subscription with FEED access included
:wave: thanks @bradchiappetta !
to clarify, does `FEED access` refer to the `Malicious feed` that comes with an "Advanced" subscription plan?
![image](https://github.com/eclecticiq/extensions-store/assets/61271590/dc0dea73-f8f6-4aed-a010-a81a0dca7020)

2023-06-07 14:43 UTC, bradchiappetta commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +- GreyNoise subscription with FEED access included
@zed-eiq : we have four feed options: benign, malicious, benign+malicious, and all indicators.  These can be added to any subscription package (we allow them to be customized), but you are correct that the "Advanced" package includes the Malicious Feed.

2023-06-07 14:51 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +- GreyNoise subscription with FEED access included
thank you!

2023-06-08 09:42 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +Using the submitted IP addresses as input and the complementary data provided by GreyNoise, this enricher creates EIQ JSON indicators with the following fields:
- don't use the word `complementary` --> this could mean that the data is provided for free, which is not the case.
- i would document as follows:

> This enricher queries the NOISE and RIOT datasets for a given IP address, and using the results produces an EIQ JSON indicator with the following fields:

2023-06-09 10:05 UTC, zed-eiq commented on extensions/greynoise/enrichments/greynoise_noise_enricher_v1/README.rst
> +    * - Field Name
please apply changes requested in https://github.com/eclecticiq/extensions-store/pull/116 to this also :pray:

2023-06-15 09:15 UTC, zed-eiq commented
LGTM! thanks!

2023-06-15 10:58 UTC, merged