Pint 925 crowdstrike enricher
eclecticiq/extensions-store pull request #87
Opened 2023-04-10 14:34 UTC by canic-eiq

2023-04-21 11:56 UTC, petarc-eiq requested changes

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/manifest.json
> +  "repository": "https://github.com/team.pint@eclecticiq.com/crowdstrike-enricher",
"repository": "https://github.com/eclecticiq/extensions-store",

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/AUTHORS.md
> +* John Doe <email@example.com>
TODO: check if and when we should put proper names and emails in authors.md

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/manifest.json
> +  "eiq_verified": false,
This should be checked too - maintainer, producer, eiq_verified and other fields.

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/manifest.json
> +      "id": "urn:eiq-edk:eclecticiq:group-ib:0.1",
"id": "urn:eiq-edk:eclecticiq:crowdstrike-enricher:1.0.0",

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/manifest.json
> +        "crowdstrike_extension"
crowdstrike_enricher

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/manifest.json
> +      "description": "Crowdstrike Falcon Intelligence Indicator Feed",
"Crowdstrike Falcon Intelligence Indicator Feed" -> "Crowdstrike Falcon Intelligence Enricher"

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/manifest.json
> +          "default": "https://api.us-2.crowdstrike.com/",
https://api.us-2.crowdstrike.com/ is the API we are using with our account, but default should be:
"https://api.crowdstrike.com"

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/process.py
> +import structlog
Run isort on this file. Run black too...

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/process.py
> +enricher_limit = 50
This is not used in EDK, remove the variable.

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/process.py
> +        log.info("Enricher started")
No need to call `log.info()` in extensions, if we're calling `self.send_info()`.

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/process.py
> +        log.info(f"Enricher finished successfully, submitting {len(extracts)} extracts")
copy/paste

No need to call log.info() in extensions, if we're calling self.send_info().

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/transformer.py
> +from typing import List
copy/paste

Run isort and black on this file.

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/utils.py
> +from furl import furl
Run isort and black in this file.

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/utils.py
> +log = structlog.get_logger(__name__)
We should check if and how we should use structlog in util and other extension files.

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/process.py
> +        self.save_enrichment_result(entities=[],extracts=extracts,raw_data="")
At the end of extension process, we need to call
```
self.save_stash()
```
because stash may be updated by oauth2service with new OAuth2 token.

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/utils.py
> +USER_AGENT_HEADER = f"EclecticIQ IC/{PLATFORM_VERSION} CrowdStrike/{EXTENSION_VERSION}"
We need to change this part, because now this data should be taken from extension manifest file.
In MainApp class we can define the header and pass it to other classes and functions:
```
user_agent = f"{self.manifest['name']} version:{self.manifest['version']}",
```

2023-04-21 11:56 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/utils.py
> +USER_AGENT_HEADER = f"EclecticIQ IC/{PLATFORM_VERSION} CrowdStrike/{EXTENSION_VERSION}"
Even better, if there's time for a minor refactor, we should create a single `requests.Session` object in MainApp class, set the hard-coded header (as suggested bellow) and pass and use that session object in Oauth2 and Crowdstrike services:
```
    "User-Agent": f"{self.manifest['name']} version:{self.manifest['version']}",
```
The two services accept different content types, so they will set the header to `"Content-Type": "application/json"` or `"Content-Type": "application/x-www-form-urlencoded"` when they use the Session object to send requests.

2023-04-26 08:19 UTC, zoranjovevski commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/LICENSE.md
> +# The MIT License (MIT)
Change to Apache license

2023-04-26 08:59 UTC, zoranjovevski commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/utils.py
> +        log.info("Started creating token for OAuth2.")
Change this also

2023-04-26 09:09 UTC, petarc-eiq commented on extensions/crowdstrike/enrichments/crowdstrike_enricher/utils.py
> +        log.info("Started creating token for OAuth2.")
@zoranjovevski `self.send_info()` isn't available outside of `MainApp` class. We could check for these logs behave and figure out what's the right way to log things like this. Sending things like "Started creating token for OAuth2." to Redis and/or Audit Log is an overkill to me, extensions should be able to have their low level logs that won't produce too much noise on a higher level. //cc @erwin-eiq

2023-05-04 11:53 UTC, zoranjovevski approved these changes

2023-05-04 12:17 UTC, merged